#!/usr/bin/env bash

# --------------------------------------------------------------------
# Build and package artifacts for including in static Docker containers for Workspace HxP
# Please see apps/workspace-hxp/DockerfileStaticResource
# -----------------------------------------------------------------

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$(pwd)"
DBP_VERSION=$( jq -r ".version" $REPO_ROOT/package.json )
HXP_VERSION=$( jq -r ".deploy.releaseVersion" $REPO_ROOT/apps/workspace-hxp/project.info.json )
PARENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

source $PARENT_DIR/job_hooks/helpers.sh

if [ -z ${WORKSPACE_HXP_ARTIFACT_NAME+x} ]; then echo "WORKSPACE_HXP_ARTIFACT_NAME is not specified"; exit 1; fi
if [ -z ${WORKSPACE_HXP_DIST_PATH+x} ]; then echo "WORKSPACE_HXP_DIST_PATH is not specified"; exit 1; fi

mkdir -p "$WORKSPACE_HXP_ARTEFACTS_DIR"

# Converting directory paths to absolute paths
WORKSPACE_HXP_ARTEFACTS_DIR="$( cd "$WORKSPACE_HXP_ARTEFACTS_DIR" && pwd )"
WORKSPACE_HXP_DIST_PATH="$( cd "$WORKSPACE_HXP_DIST_PATH" && pwd )"

# -------------------------------------------------------------------------------------------------
# Packing Workspace HxP files
# -------------------------------------------------------------------------------------------------
echo -e "\e[32mPacking Workspace HxP files ... \e[0m"
    create_zip_artefact "$WORKSPACE_HXP_DIST_PATH" "$WORKSPACE_HXP_ARTEFACTS_DIR/${WORKSPACE_HXP_ARTIFACT_NAME}-${HXP_VERSION}-dist.zip" $DBP_VERSION;
    create_zip_sha "$WORKSPACE_HXP_ARTEFACTS_DIR/${WORKSPACE_HXP_ARTIFACT_NAME}-${HXP_VERSION}-dist.zip"

# -------------------------------------------------------------------------------------------------
# Generating Workspace HxP application source code archives
# -------------------------------------------------------------------------------------------------
echo -e "\e[32mGenerating Workspace HxP application source code archives\e[0m"
    WORKSPACE_HXP_SOURCE_CODE_ZIP="${WORKSPACE_HXP_ARTEFACTS_DIR}/${WORKSPACE_HXP_ARTIFACT_NAME}-${HXP_VERSION}-source-code.zip"

    npm run mr content-src-code-zipper --silent -- --output $WORKSPACE_HXP_SOURCE_CODE_ZIP -e workspace-hxp --logLevel silly || exit 103

    echo -e "Create sha for $WORKSPACE_HXP_SOURCE_CODE_ZIP"
    create_zip_sha $WORKSPACE_HXP_SOURCE_CODE_ZIP

# -------------------------------------------------------------------------------------------------
# Cleaning up
# -------------------------------------------------------------------------------------------------
rm -f $REPO_ROOT/.tempfile
